### ISSUE TITLE
[fs.stats] BigIntな変数類は定義したうえでコメントアウトする

### ISSUE THREAD

**Issue by ahuglajbclajep** [DenkiYagi/hxnodejs#10]
> fs.stats: BigIntな変数類は、定義したうえでBigInt部分をコメントアウトしたのち、「BigIntが実装されないとだめ」みたいなコメントを入れておいてください。
> 「it should be implemented bigint」とか。

とありますが、多くは `stats.dev` のようなプロパティであり、定義するには `EitherType` で書く必要があり、具体的にどう書くのがベストなのか困っています。
また `stats.atimeNs` のような `BigInt` のみをとるプロパティも、連続で書くと改行してもコメントのブロックどうしが隣接してしまい視認しにくいです。
これについてもなにかいい案があれば教えてほしいです。

**Comment by takashiski** [comment]
1. `bigint`専用のものは定義してコメントアウト。改行はあきらめる
2. `number|bigint`のものは`number`部分のみ定義して、コメントに「TODO:bigintが実装されたらEithertype<Int,Bigint>にする」のような文言を英語でいれる

こんな感じが妥当なんじゃないかと思います。

そこにその定義で実装できない理由が書いてあれば、レビュー時に見落としたわけではないとはっきりわかるのでなぜないのかの確認作業をしなくてよいということと、何が実現できれば利用可能になるのかがわかって次の判断ができるのでよいのではないか、という考えです。
