### ISSUE TITLE
MessageChannel の型が定義できない

### ISSUE THREAD

**Issue by ahuglajbclajep** [DenkiYagi/hxnodejs#21]
[worker_threads の MessageChannel](https://nodejs.org/api/worker_threads.html#worker_threads_class_messagechannel) は `new MessageChannel()` で `{port1:MessagePort, port2:MessagePort}` なオブジェクトを返しますが、Haxeで `function new():{port1:MessagePort, port2:MessagePort}` と書くと以下のようなエラーが出ます。

> A class constructor can't have a return valuediagnostics(2)

**Comment by terurou** [comment]
コンソールで確認したら、こう出ました。

```js
> const { MessageChannel } = require('worker_threads');
undefined
> new MessageChannel()
MessageChannel {
  port1: MessagePort {
    active: true,
    refed: false,
    _events: [Object: null prototype] {
      newListener: [Function],
      removeListener: [Function]
    },
    _eventsCount: 2
  },
  port2: MessagePort {
    active: true,
    refed: false,
    _events: [Object: null prototype] {
      newListener: [Function],
      removeListener: [Function]
    },
    _eventsCount: 2
  }
}
```

普通にMessageChannel型のインスタンスが返ってきてるので、`public var port1:MessagePort;` のようにインスタンスプロパティとして定義すればよいかと思います。
