### ISSUE TITLE
Dns.hx の DnsLookupCallbackAll に関して

### ISSUE THREAD

**Issue by akitsu-sanae** [DenkiYagi/hxnodejs#5]
> Haxe3.x版の `DnsLookupCallbackAll` に余分な `DnsError` がついている？

コードを見てもどの部分を指摘しているのかいまいち分からなかったのでお手数ですが，もう少し詳しく説明してくださるとありがたいです．

@ahuglajbclajep

**Comment by ahuglajbclajep** [comment]
[以前](https://github.com/HaxeFoundation/hxnodejs/blob/34419a316f13884607ad63f3145599d3a1382a1c/src/js/node/Dns.hx#L313-L314) は `DnsError->DnsError->Array<DnsLookupCallbackAllEntry>->Void;` のようになっていたのですが、最新のコミットでは修正されているようなので無視してもらって大丈夫です。

**Comment by ahuglajbclajep** [comment]
よく見たら直ってませんでした。
https://github.com/DenkiYagi/hxnodejs/blob/dns-extern/src/js/node/Dns.hx#L313-L314

**Comment by akitsu-sanae** [comment]
理解 & 修正しました
