### ISSUE TITLE
DnsPromises, 戻り値は普通のやつのコールバックのjs.lib.Promise<T>

### ISSUE THREAD

**Issue by akitsu-sanae** [DenkiYagi/hxnodejs#9]
いまいち何を指摘されているのか分かっていません．
DnsPromises のメソッドは `Promise` を返すので，ドキュメントに `Returns: <T>` とあれば `Promise<T>` を返すようにする，ということだと思っていたのですが違うのでしょうか？

> ```
> The dns.promises API provides an alternative set of asynchronous DNS methods that return Promise objects rather than using callbacks. The API is accessible via require('dns').promises.
> 
> ```
> https://github.com/nodejs/node/blob/df936c592596855ec9ad1141692faf0dc74f46f3/lib/internal/dns/promises.js

**Comment by ahuglajbclajep** [comment]
例えば `dnsPromises.lookupService` のドキュメントには `Returns: <T>` の記載はありませんが、サンプルコードを見ると `dns.lookupService` のコールバックで受け取っていた `hostname` と `service` が伝搬しているのがわかるかと思います。
https://nodejs.org/api/dns.html#dns_dnspromises_lookupservice_address_port
https://nodejs.org/api/dns.html#dns_dns_lookupservice_address_port_callback

現在のコードは `lookupService(address:String, port:Int):Promise<Void>` のようになっていますが、例のように `hostname` と `service` を伝搬させるには `Promise<{hostname:String,service:String}>` といった形にする必要があります。

**Comment by takashiski** [comment]
たぶん私が見たタイミングだと全部Promise自体がついていなかったですね。

身もふたもないことをいうと、個人的には「テスト書いてみてうまく動いてそうだったらOK」です。
例えば、dnsPromises.lookupServiceのサンプルコードをhaxeに書き換えてコンパイル・実行してみていただけますか？

**Comment by akitsu-sanae** [comment]
修正しました．

https://github.com/DenkiYagi/hxnodejs/commit/c461592087736571a131f158c03526ed014ec64d

**Comment by ahuglajbclajep** [comment]
例えば `dnsPromises.Resolver.resolve4()` を例として挙げますが、サンプルコードでは `resolver.resolve4('example.org').then((addresses) => { ... }` のようになっています。
https://nodejs.org/api/dns.html#dns_class_dnspromises_resolver
この `addresses` は `dns.resolve4()` の `addresses` であり、例えば `Array<String>` であったりするため、`dnsPromises.Resolver.resolve4()` の戻り値は `Promise<Array<String>>` のようになるべきです。

このように、基本的には元のコールバック関数にあった `err` は消してよく、`dnsPromises.lookupService()` のような元の関数のコールバックが `err` 以外に2つ以上引数をとる(この場合 `hostname` と `service`) 関数のみ `Promise<{hostname:String,service:String}>` のようなオブジェクトの形になると思います。

最初の説明が不足気味でお手数をおかけしますが、修正お願いします。

**Comment by akitsu-sanae** [comment]
修正しました！
